### ISSUE TITLE
On first load...

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/Community-App#15]
- [ ] Play the video on first load.
- [ ] Put video behind an "intro" link (top right-hand navigation)
- [ ] Remove video icon next to Pantry, 3 questions the The Table titles

**Comment by jlandon** [comment]
@frizman21 will this video be hosted in Contentful?

**Comment by frizman21** [comment]
Probably hosted in S3, but there'll be a URL to a mp4 in Contentful.
