### ISSUE TITLE
Nuke the icons 

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/Community-App#21]
We plan to use icons for new, important or some other way to later distinguish. Don't use the default "i"

**Comment by jlandon** [comment]
@frizman21 do you want to remove all the icons from the shelf rows, or only if it's the "i" icon?

**Comment by frizman21** [comment]
Only if icon not provided... right now it feels like empty means "i"

If we want to use the "i", we'd like that option still open.

**Comment by jlandon** [comment]
Got it. So basically like this?

![simulator screen shot - iphone xs - 2019-01-16 at 10 55 19](https://user-images.githubusercontent.com/4239255/51265025-5dfd5280-197d-11e9-8563-560ae06f7fa7.png)

**Comment by frizman21** [comment]
Do you have an aversion to it – I trust you UI/UX than mine own.

Skip, Have a strong opinion?  (see picture below)

mike

--


Mike Frizzell
Director of External Technology Development
Watermark Community Church
7540 LBJ Frwy, Suite 800
Dallas, TX 75251

**Comment by jlandon** [comment]
@frizman21 I think it'd be good to shoot for having icons for every top-level shelf, but then forgo icons on all the sub-shelves. Otherwise, there's just a lot of empty space on all of those (see image). You good with that?

![simulator screen shot - iphone xs - 2019-01-16 at 11 11 01](https://user-images.githubusercontent.com/4239255/51265894-71a9b880-197f-11e9-8694-8fb7c1fe5339.png)

**Comment by frizman21** [comment]
My sense of it is that the icons are gratuitous. You aren’t doing anything to increase user efficiency (I still have to read the labels), and you’re sort of suggesting that some of the items (the ones with icons) are more important  others. But they really aren’t.

Less signal is less noise.

—-
Skipper Pickle
972.978.5807

________________________________

**Comment by frizman21** [comment]
Mr. Landon,

If you’re good with dropping the icons, let’s do it!

mike

--


Mike Frizzell
Director of External Technology Development
Watermark Community Church
7540 LBJ Frwy, Suite 800
Dallas, TX 75251


From: Skipper Pickle <spickle@watermark.org>
Date: Wednesday, January 16, 2019 at 11:43 AM
To: Mike Frizzell <mfrizzell@watermark.org>, watermarkchurch/Community-App <reply@reply.github.com>, watermarkchurch/Community-App <community-app@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [watermarkchurch/Community-App] No default icon (#21)

My sense of it is that the icons are gratuitous. You aren’t doing anything to increase user efficiency (I still have to read the labels), and you’re sort of suggesting that some of the items (the ones with icons) are more important  others. But they really aren’t.

Less signal is less noise.

—-
Skipper Pickle
972.978.5807

________________________________

**Comment by jlandon** [comment]
@frizman21 sounds good. Removing the icons makes this screen feel a little bland to me, but we can maybe evaluate the design again later

![simulator screen shot - iphone xs - 2019-01-16 at 13 23 23](https://user-images.githubusercontent.com/4239255/51273278-f271b000-1991-11e9-8c51-61fcb392bc1c.png)
