### ISSUE TITLE
Title of app "Watermark Community Groups"

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/Community-App#22]

**Comment by jlandon** [comment]
@frizman21 just updated it in App Store Connect. Given the length of that name though, you still good with "Community" as the name below the app icon?

**Comment by frizman21** [comment]
I'm not sure what that means - like hte name on the icon on your phone? (if so, yes... that's fine)

**Comment by frizman21** [comment]
@jlandon

**Comment by jlandon** [comment]
@frizman21 yep, the app name in the App Store will be "Watermark Community Groups", but the name below the icon on the phone will be "Community"
