### ISSUE TITLE
Abbreviated/Shortened YouTube Links don't work.

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/Community-App#37]
Works:
https://www.youtube.com/watch?v=YESpK-4Vlf8

Doesn't work:
https://youtu.be/YESpK-4Vlf8

**Comment by jlandon** [comment]
Supported formats:
```
http://www.youtube.com/watch?v=:id
http://www.youtube.com/v/:id
http://youtu.be/:id
```

Fixed in db8ce99f274074f624b417cb7acab2a6ca4740eb (v1.1.1 build)
